### ISSUE TITLE
Base switch to Lineage OS

### ISSUE THREAD

**Issue by jbruechert** [plasma-phone-packaging/CM#11]
As you probably know, CyanogenMod is dead, or at least their services are down. The developers decided to continue their work under a new name, and as a new Github organization: https://github.com/lineageos. This is more a formal issue, but I think it would be useful to change plasma-mobile's base to Lineage OS, when they have their new infrastructure up.

**Comment by bhush9** [comment]
Unrelated earlier, but now relevant issue : https://phabricator.kde.org/T4944

Lets track this at phabricator
