### ISSUE TITLE
what's the login password?

### ISSUE THREAD

**Issue by mu-dao** [plasma-phone-packaging/CM#12]
I had start plasma and it shows a line:
ubuntu-phablet login: 
I type phablet as login username,but what's the password?
Thank you!

**Comment by star-buck** [comment]
Pwd is 1234

**Comment by mu-dao** [comment]
I use:
username:phablet
password:1234
but it still tell me Login incorrect

**Comment by bhush9** [comment]
Is it neon flavor or arch flavor?

**Comment by mu-dao** [comment]
I download from : http://mobile.neon.pangea.pub:8080/job/img_phone_xenial_armhf/lastSuccessfulBuild/artifact/result/livecd..rootfs.tar.gz

**Comment by bhush9** [comment]
More up-to-date images are available at : http://neon.plasma-mobile.org/rootfs/

**Comment by star-buck** [comment]
Please go to plasma-mobile.org for latest imgs.

**Comment by mu-dao** [comment]
I download the latest imgs and now I can login correctly.
Thanks!
